### ISSUE TITLE
Preregistration Template Evaluation

### ISSUE THREAD

**Issue by egouldo** [egouldo/EcoConsPreReg#48]
- [ ] Circulate template to reviewers
- [ ] Can circulate both template in word format
- [ ] And template in shiny app format
- [ ] Will need to circulate a document explaining how the process works... This might be some variation on the document I sent to Chris explaining the adaptive preregistration methodology, OR it could be the draft manuscript... will need to:
- [ ] Check with supervisors as to what they think the best strategy would be.
